name: BinhKyTang
favicon: null
layout_spectrum: 0.4088151757605374
typography_spectrum: 0.007860443089157343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.42945247841998935
  lightness: 0.040456830989569426
  saturation: 0.23623432987369597
  rhythmicContrast: 0.7862644614651799
purpose: []
